# mkdocs.yml
site_name: aussiebb
theme:
  name: "material"

site_url: https://yaleman.github.io/aussiebb/
repo_name: "yaleman/aussiebb"
repo_url: "https://github.com/yaleman/aussiebb"

plugins:
  - search:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
      # watch:
      # - "aussiebb/"

nav:
  - "Home": README.md
  - "API Documentation": aussiebb.md
  - Multifactor: mfa.md
  - Changelog: CHANGELOG.md
  - Releasing: release.md
